#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - ufw
write_files:
- path: /etc/environment
  content: |
    CALLBACK_ID="$CALLBACK_ID"
    CALLBACK_URL="$CALLBACK_URL"
  append: true
runcmd:
  - [curl, "$CALLBACK_URL?state=configuration-init&serverId=$CALLBACK_ID"]
  - [curl, -fsSL, "https://get.docker.com", -o, /root/get-docker.sh]
  - [sh, "/root/get-docker.sh"]
  - [curl, -fsSL, "$BAHS_SCRIPT", -o, /root/init-vpn-server.sh]
  - [bash, "/root/init-vpn-server.sh"]
  - [curl, -v, "$FINAL_CALLBACK"]
output:
    init:
        output: "> /var/log/cloud-init.out"
        error: "> /var/log/cloud-init.err"
    config: "tee -a /var/log/cloud-config.log"
    final:
        - ">> /var/log/cloud-final.out"
        - "/var/log/cloud-final.err"